### ISSUE TITLE
TODO List Part 1

### ISSUE THREAD

**Issue by 0999312** [0999312/Duan#1]
顺序代表优先级。
————————————————————————
- [ ] net.minecraftforge.common.loot 全部文件，不分优先级。
- [ ] net.minecraftforge.common.extensions 全部文件，不分优先级。
- [ ] net.minecraftforge.common.crafting 全部文件，优先翻译CraftingHelper.java。
- [ ] net.minecraftforge.common.util.RecipeMatcher.java
- [ ] net.minecraftforge.common.ForgeHooks.java
- [ ] net.minecraftforge.common.data.SoundDefinitionsProvider.java
- [ ] net.minecraftforge.common.data.SoundDefinition.java
- [ ] net.minecraftforge.common.ToolType.java
- [ ] net.minecraftforge.common.PlantType.java
